POST http://localhost:8092/tealeaves
Content-Type: application/json

{
    "name": "english breakfast",
    "type": "black",
    "suggestedAmount": "5 g",
    "suggestedWaterTemperature": "99 °C",
    "suggestedSteepingTime": "3 min"
}
