global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'demo-app'
      static_configs:
          - targets: ['host.docker.internal:4567']
    - job_name: 'eureka'
    #   scheme: 'https'
      metrics_path: '/actuator/prometheus'
      eureka_sd_configs:
          - server: http://host.docker.internal:8761/eureka
    - job_name: 'tempo'
      static_configs:
        - targets: ['host.docker.internal:3200']
